### PR TITLE
Add allowed fixmes for hhvm 4.62

### PR DESCRIPTION
**Pull request by lexidor**

### CODE REVIEW

**Comment by lexidor** [comment]
```
running HHBBC...
running HHBBC took 0'00" (12575 us) wall time
creating binary HHBC files took 0'00" (13353 us) wall time
running hphp took 0'02" (2651844 us) wall time

std::exception: More than one function with the name
Facebook\\HHAST\\__Private\\hhast_inspect_main_async.
In vendor/hhvm/hhast/bin/hhast-inspect.hack and 
   vendor/bin/hhast-inspect.hack

hphp failed
running hphp took 0'02" (2660893 us) wall time
```

We can't compile hhbbc because the symlink that composer made creates duplicate definitions.
Pretty weird, I can't remember that we've ever had this problem.

**Comment by fredemmott** [comment]
Yep, regression in 4.62, does not repro on 4.61

**Comment by fredemmott** [comment]
https://github.com/facebook/hhvm/issues/8719

**Comment by fredemmott** [comment]
FB T68775322

**Comment by fredemmott** [comment]
Landed a workaround - @lexidor  can you rebase please?

**Pull request merged**
